model_name_or_path: outputs/instella-3b-long-sft/step250-hf
use_flash_attn: true
gradient_checkpointing: true
dataset_mixer:
    allenai/olmo-2-1124-7b-preference-mix: 1.0
tokenizer_name: outputs/instella-3b-long-sft/step250-hf
use_slow_tokenizer: false
max_seq_length: 2048
preprocessing_num_workers: 16
per_device_train_batch_size: 8
# gradient_accumulation_steps: 16 # designed for 8 GPUs, so batch size 128
gradient_accumulation_steps: 2 # designed for 32 GPUs, so batch size 128
learning_rate: 5.0e-7
lr_scheduler_type: linear
warmup_ratio: 0.1
weight_decay: 0.0
num_train_epochs: 1
output_dir: outputs/instella_3b_long_dpo
with_tracking: true
report_to:
  - wandb
logging_steps: 1
use_lora: false
dpo_loss_type: dpo_norm
dpo_beta: 5
checkpointing_steps: 1000
hf_metadata_dataset: allenai/olmo-instruct-evals
add_bos: true
hf_repo_revision: instella_3b_long_dpo